
name: Build and Run Intragration Tests

on:
  push:
    branches: [ "staging" ]
  

jobs:
  build_integration_tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the reposity
      uses: actions/checkout@v4
    - name: Setup .NET Version 6
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Execute Integration Tests
      run: dotnet test SoftUniBazar.IntegrationTests/SoftUniBazar.IntegrationTests.csproj --no-build --verbosity normal
